// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyKhachSan.Data;
#nullable disable
namespace QuanLyKhachSan.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260710115249_AddDateOfBirthToEmployee")]
    partial class AddDateOfBirthToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
            modelBuilder.Entity("QuanLyKhachSan.Models.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2");
                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");
                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");
                    b.Property<int>("Role")
                        .HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.HasKey("Id");
                    b.ToTable("Accounts");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("Adult")
                        .HasColumnType("int");
                    b.Property<string>("BookingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");
                    b.Property<DateTime>("CheckOutDate")
                        .HasColumnType("datetime2");
                    b.Property<int>("Children")
                        .HasColumnType("int");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");
                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(18,2)");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<int>("Status")
                        .HasColumnType("int");
                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("CustomerId");
                    b.ToTable("Bookings");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.BookingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("BookingId")
                        .HasColumnType("int");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<int>("NumberOfNights")
                        .HasColumnType("int");
                    b.Property<decimal>("PricePerNight")
                        .HasColumnType("decimal(18,2)");
                    b.Property<int>("RoomId")
                        .HasColumnType("int");
                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("BookingId");
                    b.HasIndex("RoomId");
                    b.ToTable("BookingDetails");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("AccountId")
                        .HasColumnType("int");
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("AccountId")
                        .IsUnique();
                    b.ToTable("Customers");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("AccountId")
                        .HasColumnType("int");
                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
                    b.Property<string>("Avatar")
                        .HasColumnType("nvarchar(max)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");
                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");
                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");
                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");
                    b.Property<bool>("Status")
                        .HasColumnType("bit");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("AccountId")
                        .IsUnique();
                    b.ToTable("Employees");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("BookingId")
                        .HasColumnType("int");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<decimal>("DiscountPercent")
                        .HasColumnType("decimal(18,2)");
                    b.Property<string>("InvoiceCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");
                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<decimal>("RoomAmount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<decimal>("ServiceAmount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("decimal(18,2)");
                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("BookingId")
                        .IsUnique();
                    b.ToTable("Invoices");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");
                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");
                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");
                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("InvoiceId");
                    b.ToTable("Payments");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<int>("Rating")
                        .HasColumnType("int");
                    b.Property<int>("RoomId")
                        .HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("CustomerId");
                    b.HasIndex("RoomId");
                    b.ToTable("Reviews");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");
                    b.Property<int>("Floor")
                        .HasColumnType("int");
                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");
                    b.Property<decimal>("PriceDay")
                        .HasColumnType("decimal(18,2)");
                    b.Property<decimal>("PriceWeek")
                        .HasColumnType("decimal(18,2)");
                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");
                    b.Property<double>("RoomSize")
                        .HasColumnType("float");
                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");
                    b.Property<int>("Status")
                        .HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("RoomTypeId");
                    b.ToTable("Rooms");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.RoomImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Caption")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");
                    b.Property<int>("RoomId")
                        .HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("RoomId");
                    b.ToTable("RoomImages");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<double>("Area")
                        .HasColumnType("float");
                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18,2)");
                    b.Property<string>("BedType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<int>("MaxOccupancy")
                        .HasColumnType("int");
                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("RoomTypes");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");
                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");
                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.ToTable("Services");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.ServiceBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("BookingId")
                        .HasColumnType("int");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");
                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");
                    b.Property<int>("Quantity")
                        .HasColumnType("int");
                    b.Property<int>("ServiceId")
                        .HasColumnType("int");
                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");
                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");
                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("BookingId");
                    b.HasIndex("ServiceId");
                    b.ToTable("ServiceBookings");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Booking", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Customer");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.BookingDetail", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("QuanLyKhachSan.Models.Room", "Room")
                        .WithMany("BookingDetails")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Booking");
                    b.Navigation("Room");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Customer", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Account", "Account")
                        .WithOne("Customer")
                        .HasForeignKey("QuanLyKhachSan.Models.Customer", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Account");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Employee", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Account", "Account")
                        .WithOne("Employee")
                        .HasForeignKey("QuanLyKhachSan.Models.Employee", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Account");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Invoice", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Booking", "Booking")
                        .WithOne("Invoice")
                        .HasForeignKey("QuanLyKhachSan.Models.Invoice", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Booking");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Payment", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Invoice");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Review", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Customer", "Customer")
                        .WithMany("Reviews")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("QuanLyKhachSan.Models.Room", "Room")
                        .WithMany("Reviews")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Customer");
                    b.Navigation("Room");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Room", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.RoomType", "RoomType")
                        .WithMany("Rooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("RoomType");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.RoomImage", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Room", "Room")
                        .WithMany("RoomImages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Room");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.ServiceBooking", b =>
                {
                    b.HasOne("QuanLyKhachSan.Models.Booking", "Booking")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.HasOne("QuanLyKhachSan.Models.Service", "Service")
                        .WithMany("ServiceBookings")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Booking");
                    b.Navigation("Service");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Account", b =>
                {
                    b.Navigation("Customer");
                    b.Navigation("Employee");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Booking", b =>
                {
                    b.Navigation("BookingDetails");
                    b.Navigation("Invoice");
                    b.Navigation("ServiceBookings");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Customer", b =>
                {
                    b.Navigation("Bookings");
                    b.Navigation("Reviews");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Invoice", b =>
                {
                    b.Navigation("Payments");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Room", b =>
                {
                    b.Navigation("BookingDetails");
                    b.Navigation("Reviews");
                    b.Navigation("RoomImages");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.RoomType", b =>
                {
                    b.Navigation("Rooms");
                });
            modelBuilder.Entity("QuanLyKhachSan.Models.Service", b =>
                {
                    b.Navigation("ServiceBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
